### ISSUE TITLE
Amazing progress!

### ISSUE THREAD

**Issue by olof-nord** [devolo/Cockpit-open-frontend#12]
Hello devolo team,

I just had to compliment the team and the recent development efforts!

The adjusted/new(?) device icons and dark mode looks absolutely great.

Perhaps its worth updating the screenshot in the [readme](https://github.com/devolo/cockpit_open_frontend/blob/develop/images/overviewENG.png) as a way to show the work?

**Comment by julienAhn** [comment]
Hello Olof,

We are happy that you like the design!
Great suggestion! From now on we will update the screenshots in the README each time changes in the design are made.
We just added new screenshots: bf37b52eeef85595dab47fd4bf4d645db91ca6b9

We wish you a happy easter!
