### ISSUE TITLE
Linux support?

### ISSUE THREAD

**Issue by olof-nord** [devolo/Cockpit-open-frontend#5]
Hello devolo,

I found this repo, while looking for the devolo Cockpit source code.

In the readme, Linux is listed as a supported platform, however it does not work for me.

I understand this is probably a WIP project, but throught I should let you know anyhow.
Your open-source approach to the re-write is greatly appreciated.

```log
➜  cockpit_open_frontend git:(develop) ✗ flutter run -d linux
No devices found with name or id matching 'linux'
➜  cockpit_open_frontend git:(develop) ✗
```

```log
➜  cockpit_open_frontend git:(develop) flutter build linux 
Downloading linux-x64/linux-x64-flutter-gtk tools...             2,443ms
Downloading linux-x64-profile/linux-x64-flutter-gtk tools...      1,529ms
Downloading linux-x64-release/linux-x64-flutter-gtk tools...      1,077ms
Running "flutter pub get" in cockpit_open_frontend...              11.2s
"build linux" is not currently supported. To enable, run "flutter config --enable-linux-desktop".
➜  cockpit_open_frontend git:(develop) ✗
```

**Comment by olof-nord** [comment]
System info: Linux 5.16.0-arch1-1 #1 SMP PREEMPT Mon, 10 Jan 2022 20:11:47 +0000 x86_64 GNU/Linux

GNOME Shell 41.3

Flutter 2.8.1 • channel stable • https://github.com/flutter/flutter.git
Framework • revision 77d935af4d (4 weeks ago) • 2021-12-16 08:37:33 -0800
Engine • revision 890a5fca2e
Tools • Dart 2.15.1

**Comment by Calorine** [comment]
Hello Olof,

Thank you for letting us know.
Could you provide us with your output of "`flutter doctor`" and "`flutter devices`"?
For flutter, desktop support must be added separately for each platform. (see: https://docs.flutter.dev/desktop#set-up)
In this case: `flutter config --enable-linux-desktop`

Let us know if this helped you.

**Comment by olof-nord** [comment]
Hello Calorine,

many thanks for getting back to me.

I ran `flutter config --enable-linux-desktop`, which fixed my initial problem.

There seems to be some issue with one file, but I will close this issue as my initial question is answered.

The details of the issue is as follows:

Building and running the application seems to get stuck on [lib/shared/informationDialogs.dart:954](https://github.com/devolo/cockpit_open_frontend/blob/develop/lib/shared/informationDialogs.dart#L954).

The getter `standart` called from the context is not defined - looking into this it might have something to do with my flutter version - I am using the latest version (see my previous comment for all details). If a specific flutter version is required, perhaps that could be mentioned in the readme?

**Comment by Calorine** [comment]
Perfekt.

About the other error: It is in the process of being fixed. 
Regarding the Flutter version: We always try to work with the latest Flutter version.
